version: '3.8'

services:
  database:
    platform: linux/x86_64
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:latest
    tty: true
    stdin_open: true
    container_name: meilisearch
    environment: 
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
    ports:
      - "7700:7700"

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - meilisearch
      - database
